name:                parse
version:             0.1.1.0
github:              "jlagarespo/parse"
license:             BSD3
author:              "Jacob Lagares Pozo"
maintainer:          "jlagarespo@protonmail.com"
copyright:           "Jacob Lagares Pozo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Simple way to parse strings with Python-like format strings.
category:            Parser

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please refer to the README file that ships with this package.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - template-haskell == 2.16.0.0
  - split == 0.2.3.4

tests:
  parse-test:
    main: Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - parse
    - tasty == 1.4.2
    - tasty-hunit == 0.10.0.3

default-extensions:
- FlexibleInstances
- TemplateHaskell
- LambdaCase
